# Species Distribution Modelling Configuration

# Data paths
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  models: "data/sdm_models"
  tuning_dir: "data/sdm_tuning"
  predictions: "data/sdm_predictions"
  model_config: "model_config.yml"
  variables_config: "variables_config.yml"
  occurence_data: "data/processed/bats-tidy.geojson"
  background_points: "data/processed/background-points.geojson"
  boundary: "data/processed/boundary.geojson"
  grid_points: "data/evs/grid-points.parquet"
  evs: "data/processed/evs"
  ev_tiff: "data/evs/evs-to-model.tif"

# Spatial configuration
spatial:
  top: 646900
  left: 313000
  crs: "EPSG:27700"
  resolution: 100
  study_area_buffer: 7000

# Coordinate reference system
crs: "EPSG:27700" # OSGB1936 / British National Grid

# MLflow configuration
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "species_sdm_experiment"
