name: bats

channels:
  - conda-forge
  - pytorch
  - defaults
  - apple

dependencies:
  - python=3.11
  - dask
  - ipykernel
  - xarray
  - rioxarray
  - geopandas
  - numpy
  - pandas
  - elapid
  - pytest
  - aiohttp
  - tqdm
  - earthengine-api
  - geemap
  - seaborn
  - scikit-learn
  - mlflow
  - pytorch=2.1
  - torchvision=0.16
  - richdem
  - openpyxl
  - pyarrow
  - plotly
  - rasterio
  - pip
  - pip: 
    - pyhere
    - nest-asyncio
    - os-grid-reference
    - shiny
    - shinyswatch
    - shinywidgets
    - ipyleaflet
    - localtileserver
    - google-cloud-storage
