model:
  record_age_years: 20

  maxent:
    feature_types:
      - "linear"
      - "hinge"
    beta_multiplier: 3.0
    beta_lqp: 1.0
    beta_hinge: 1.0
    beta_threshold: 1.0
    beta_categorical: 1.0
    n_hinge_features: 10
    n_threshold_features: 10
    clamp: true
    convergence_tolerance: 1.0e-5
    use_lambdas: "best"
    n_lambdas: 100
    class_weights: "balanced"
    tau: 0.5
    transform: "cloglog"

  sampling:
    min_presence: 15
    subset_occurrence: null
    subset_background: false
    order_by_density_for_subset: true
    sample_weight_n_neighbors: 5
    grid_size_m: 2000
    background:
      factor: 10
      min_bg: 1000
      max_bg: 10000

  background:
    n_background_points: 8000
    background_method: "contrast"
    background_value: 0.025
    sigma: 6.5
    transform_method: "presence"


