variables:
  roster:
    - "climate_stats_wind_ann_avg"
    - "terrain_dtm"
    - "climate_stats_temp_ann_avg"
    - "climate_stats_prec_ann_avg"
    - "climate_bioclim_bio_3"
    - "os_distance_distance_to_buildings"
    - "terrain_stats_slope"
    - "terrain_stats_twi"
    - "climate_bioclim_bio_9"
    - "ceh_landcover_arable"
    - "ceh_landcover_improved_grassland"
    - "vom_vegetation_height_max"
    - "os_cover_water"
    - "terrain_stats_aspect_northness_slope"
    - "terrain_stats_aspect_eastness_slope"
    - "terrain_stats_tpi"
    - "ceh_landcover_wetland"
    - "os_distance_distance_to_major_roads"
    - "ceh_landcover_upland_heathland"
    - "ceh_landcover_suburban"
    - "ceh_landcover_grassland"
    - "ceh_landcover_urban"
    - "os_distance_distance_to_water"
    - "ceh_landcover_coniferous_woodland"
    - "ceh_landcover_arable_500m"
    - "vom_vegetation_height_max_500m"
    - "os_cover_water_500m"
    - "ceh_landcover_grassland_500m"
    - "ceh_landcover_wetland_500m"
    - "ceh_landcover_suburban_500m"
    - "ceh_landcover_urban_500m"
    - "ceh_landcover_improved_grassland_500m"
    - "ceh_landcover_coniferous_woodland_500m"
    - "bgs_coast_distance_to_coast"
    - "climate_bioclim_bio_7"
    - "climate_bioclim_bio_8"
    - "climate_stats_temp_ann_var"
    - "terrain_stats_roughness"
    - "vom_vegetation_height_mean"
    - "vom_vegetation_height_mean_500m"
    - "ceh_landcover_broadleaved_woodland"
    - "ceh_landcover_broadleaved_woodland_500m"
  activity_feature_sets:
    In flight:
      - "ceh_landcover_improved_grassland"
      - "ceh_landcover_suburban"
      - "bgs_coast_distance_to_coast"
      - "ceh_landcover_arable"
      - "ceh_landcover_suburban_500m"
      - "ceh_landcover_arable_500m"
      - "climate_bioclim_bio_7"
      - "vom_vegetation_height_max"
      - "terrain_stats_slope"
      - "ceh_landcover_broadleaved_woodland"
      - "climate_bioclim_bio_9"
      - "climate_stats_temp_ann_var"
      - "os_cover_water"
      - "climate_bioclim_bio_3"
      - "ceh_landcover_improved_grassland_500m"
      - "ceh_landcover_urban"
      - "climate_stats_prec_ann_avg"
      - "climate_stats_temp_ann_avg"
      - "os_distance_distance_to_major_roads"
      - "terrain_dtm"
      - "os_distance_distance_to_buildings"
      - "ceh_landcover_urban_500m"
      - "climate_stats_wind_ann_avg"
    Roost:
      - "ceh_landcover_suburban"
      - "vom_vegetation_height_max"
      - "os_distance_distance_to_buildings"
      - "vom_vegetation_height_max_500m"
      - "ceh_landcover_suburban_500m"
      - "ceh_landcover_wetland"
      - "ceh_landcover_coniferous_woodland"
      - "ceh_landcover_grassland"
      - "terrain_stats_twi"
      - "climate_bioclim_bio_9"
      - "os_cover_water"
      - "ceh_landcover_urban"
      - "ceh_landcover_wetland_500m"
      - "ceh_landcover_urban_500m"
      - "os_distance_distance_to_water"
      - "ceh_landcover_coniferous_woodland_500m"
