# Default configuration for species-sdm

paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  results: "results/"

crs: "EPSG:27700" # OSGB1936 / British National Grid

mlflow:
  tracking_uri: "mlruns"
  experiment_name: "species_sdm_experiment"

hyperparameters:
  maxent:
    # Add MaxEnt specific hyperparameters here
    regularization_multiplier: 1.0

  # Add model specific hyperparameters here 