# Default configuration for species-sdm

paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  models: "data/sdm_models"
  predictions: "data/sdm_predictions"
  occurence_data: "data/processed/bats-tidy.geojson"
  background_points: "data/processed/background-points.geojson"
  boundary: "data/processed/boundary.geojson"
  grid_points: "data/evs/grid-points.parquet"
  evs: "data/processed/evs"
  ev_tiff: "data/evs/evs-to-model.tif"

crs: "EPSG:27700" # OSGB1936 / British National Grid

mlflow:
  tracking_uri: "sqlite:///data/sdm_models/mlflow.db"
  experiment_name: "species_sdm_experiment"

hyperparameters:
  maxent:
    # Add MaxEnt specific hyperparameters here
    regularization_multiplier: 1.0

  # Add model specific hyperparameters here 